// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `rt`

/// 启动 weft-core:加载配置、启动 WASM packages、绑定 HTTP(给 webview 用)。
/// project_root: 项目根目录绝对路径(含 config/config.toml + packages/ + data/)。
/// 返回空字符串=成功,非空=错误信息。
Future<String> startCore({required String projectRoot}) =>
    RustLib.instance.api.crateFfiStartCore(projectRoot: projectRoot);

/// 统一 RPC 调用:传入 JSON RequestEnvelope → 返回 JSON ResponseEnvelope。
/// 与 /rpc 端点格式一致,但走进程内 HTTP loopback(Phase 3a)。
Future<String> rpcCall({required String requestJson}) =>
    RustLib.instance.api.crateFfiRpcCall(requestJson: requestJson);

/// 停止 core。
Future<void> stopCore() => RustLib.instance.api.crateFfiStopCore();

/// 检查 core 是否在跑。
Future<bool> isCoreRunning() => RustLib.instance.api.crateFfiIsCoreRunning();
